In [1]:
import numpy as np
import pandas as pd
# creating a dataframe

In [2]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [3]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [4]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)

In [5]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [8]:
columns = ["Name","Age","city","salary"]
df2 = pd.DataFrame(data_list,columns = columns)

In [9]:
df2

    Name  Age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
# selection and indexing of columns

In [11]:
df2

    Name  Age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [12]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [13]:
df2[["Name","city"]]

    Name      city
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [14]:
# create a new columns

In [15]:
df2["Designation"] = ["Doctor","Eng.","Civil servent","Minister"]
df2

    Name  Age      city  salary    Designation
0   John   28  New York   65000         Doctor
1   Anna   34     Paris   70000           Eng.
2  Peter   29    Berlin   62000  Civil servent
3  Linda   42    London   85000       Minister

In [16]:
# How to remove column

In [17]:
df2.drop('Designation',axis = 1)

    Name  Age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
df2

    Name  Age      city  salary    Designation
0   John   28  New York   65000         Doctor
1   Anna   34     Paris   70000           Eng.
2  Peter   29    Berlin   62000  Civil servent
3  Linda   42    London   85000       Minister

In [19]:
df2.drop('Designation',axis = 1 , inplace = True)

In [20]:
df2

    Name  Age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [21]:
df2.drop(["city","salary"],axis = 1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [22]:
df2.drop(0 , axis = 0)

    Name  Age    city  salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [23]:
# selecting a row

In [24]:
df2.loc[0]

Name          John
Age             28
city      New York
salary       65000
Name: 0, dtype: object

In [25]:
df2.loc[[0,1]]

   Name  Age      city  salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [26]:
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [27]:
# selecting subsets of rows and columns

In [30]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [31]:
# conditional section

In [32]:
df2

    Name  Age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [33]:
#I only want to see those people whose age is above 30

In [34]:
df2[df2["Age"] >30]

    Name  Age    city  salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [35]:
#I only want poeple whose age is above 30 and their city must be paris

In [37]:
df2[(df2["Age"] >30 ) & ( df2["city"] == 'Paris')]

   Name  Age   city  salary
1  Anna   34  Paris   70000