In [1]:

import numpy as np 
import pandas as pd

In [2]:

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [3]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [4]:
# finding Missing data

In [5]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [7]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [8]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [9]:
# removing missing data

In [10]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [22]:
df.dropna()  # it drop data row wise

     A  B    C    D
0  1.0  1  1.0  1.0

In [13]:
df.dropna(thresh= 3)  # 3 -- null values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [14]:
df.dropna(thresh=4)

     A  B    C    D
0  1.0  1  1.0  1.0

In [15]:
df.dropna(thresh=5)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [16]:
# filling the missing data

In [17]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [23]:
df.fillna(0)  #  have to use inplace true to apply in real data  
# it fill data column wise

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [21]:
values = {'A':0 , 'B':100 , 'C':300 , 'D':400}
df.fillna(value = values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [24]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [27]:
df.fillna(df.mean())  # it fill na with the mean value of the same row non na value

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0